README.md
configure.ac
src/libltfs/ltfslogging.c
src/libltfs/ltfssnmp.c
src/libltfs/ltfssnmp.h

Add a switch to disable SNMP support because it can't be supported under OSX (macOS) Homebrew environment. --disable-snmp is needed to build on OSX (macOS) Homebrew environment.

Add a switch to disable SNMP support.

---

README.md
conf/Makefile.am
configure.ac
src/Makefile.am

To support wider platforms, I decided to switch default backend from
lin_tape to sg, because lin_tape only supports a few platform.
After this change, sg backend is the default in Linux and iokit backend
is the default in OSX. lin_tape backend is built only when
`--enable-lintape` is specified in configure script. And lin_tape backend
is set default when `DEFAULT_TAPE=lin_tape` is specified in configure
script.

Make lin_tape driver optional 

---

ltfs.pc.in

Adjust include path for use libltfs from outside of this project.
User can include it like `#include <libltfs/ltfs.h>`
Fixes #issue_no

Adjust pkg-config data for include path

---

src/tape_drivers/ibm_tape.c

src/tape_drivers/ibm_tape.c makes a build break on MinGW. This fix avoid
this with dummy key data.

Avoid build break on non-unix environment

---

src/libltfs/xml_libltfs.h
src/libltfs/xml_reader_libltfs.c
src/libltfs/xml_writer_libltfs.c

Cleaning LTFS parser here to have clean fix for missing "percentencoded" attribute in the LTFS index.
The changes are
- Add `static` to the local functions in the LTFS label parser
- Add `static` to the local functions in the LTFS index parser
- Change function order to reduce forward reference as much as possible
Preparation of #4 

Cleaning LTFS label and LTFS index parser

---

src/libltfs/xml_writer_libltfs.c

The character set for percent encoding is wrong.
- Change "...\..." to "...\\..." for handling '\' correctly.
- This warning was introduced by the fix of issue #4  (30b3575)
Remove warning introduced into 30b3575

Remove warning into 30b3575

---

configure.ac

The standard of the C language does not specify plain 'char' is unsigned
or signed. In gcc(x86_64) it is signed, but it is unsigned in
gcc(ppc64le) by default.
This change specifies the plain 'char' is signed in compiler option.
This specification is needed to run LTFS on ppc64le machine.

Specify char as "signed char" explicitly

---

messages/tape_common/root.txt
messages/tape_iokit_ibmtape/root.txt
messages/tape_linux_lin_tape/root.txt
messages/tape_linux_sg_ibmtape/root.txt
src/tape_drivers/ibm_tape.c
src/tape_drivers/ibm_tape.h
src/tape_drivers/linux/lin_tape/lin_tape_ibmtape.c
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
src/tape_drivers/osx/iokit-ibmtape/iokit_ibmtape.c
src/tape_drivers/tape_drivers.h

To secure the M8 formatted tape's density code, reject initial F/W of IBM LTO8 drive.
- Fix of issue #19
- Move the functions to control FW level rejection to common area
To secure the M8 formatted tape's density code, reject initial F/W of IBM LTO8 drive. If all FW level is accepted, LTFS changes M8 tape back to L7 tape at format operation in the initial IBM LTO8 FW level.
Fixes #19

Clip the initial IBM LTO8 drive's FW level

---

src/libltfs/ltfslogging.h

Make tiny correction against #22.
Revert ltfsmsg_buffer() not to support message checker.
At this time, we assume this function is used for messages with no arguments.

Tiny correction of message function.

---

src/tape_drivers/ibm_tape.c

Currently barcode label `XXXXXXM8` is not supported correctly.
ibm tape drive backends should return mountable information correctly.
In this fix, ibm tape drive backends returns correct hint information for `XXXXXXM8`.

Handle M8 labeled tape correctly

---

src/tape_drivers/osx/iokit-ibmtape/iokit_ibmtape.c

Correction one message foe message checker.
- Fix the side effect of #22 
I forget to change one message in #22. 
Fixes #22

Correct argument of ltfsresult() for message checker

---

configure.ac
src/libltfs/ltfs.h

- Update version number in configure.ac and ltfs.h
IBM released IBM Spectrum Archive SDE 2.4.0.1 (10062) in 2018/01/12 at
fc26267. So the LTFS project release same version based on fc26267.
- New release

Update version number to 2.4.0.1 (10062)

---

README.md
messages/internal_error/root.txt
messages/libltfs/root.txt
messages/tape_generic_file/root.txt
messages/tape_linux_sg_ibmtape/root.txt
src/libltfs/arch/errormap.c
src/libltfs/ltfs_error.h
src/libltfs/tape.h
src/tape_drivers/generic/file/filedebug_tc.c
src/tape_drivers/ibm_tape.c
src/tape_drivers/ibm_tape.h
src/tape_drivers/linux/lin_tape/lin_tape_ibmtape.c
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.h
src/tape_drivers/linux/sg-ibmtape/sg_scsi_tape.c
src/tape_drivers/osx/iokit-ibmtape/iokit_ibmtape.c
validate_error_messages.py

- Introduce path failover function in the sg-ibmtape backend
This is the first drop of path failover function (Linux sg-ibmtape only). The concept is
- The sg backend returns an error when path switch happened
- The libltfs execute "re-validation" operation when it receives a path
switch related error
There is no command re-issue into the sg backend. The sg backend does following things.
- Detect connection loss from sg driver call
- Search new device when connection loss happens
- Recover drive reservation in the new path

Introduce path failover function in the sg-ibmtape backend

---

messages/bin_ltfs/root.txt
src/main.c

Currently ltfs falis to mount LTO5 tape on LTO7 drive. I enbugged this corruption from 2.2.2.0 to 2.4.0.0.
- Fix of issue #33 
Currently ltfs falis to mount LTO5 tape on LTO7 drive.  This is a basic functionality breakage. I want to fix as soon as possible.
Following tests are made
- Mount LTO5 tape on LTO7 drive as read-only mode
- Mount LTO6 tape on LTO6 drive as read-write  mode
Fixes #33

Handle read-only combination of tape and drive

---

src/libltfs/plugin.c

Fix to print plugin help correctly. It is broken when teh tape backend
name prefix from "driver" to "tape".
This fix is a part of the freebsd patch provided by Spectra Logic (Nor merged yet!!). I will backport this portion to v2.4.0 branch.
Small correction to print help text correctly. No issue is reported yet.

Tiny fix of plugin help print

---

messages/bin_ltfs/root.txt
src/main.c

This pull request is the same one to be applied to v2.4.0 by #34. But this request is for master branch.
Currently ltfs falis to mount LTO5 tape on LTO7 drive. I enbugged this corruption from 2.2.2.0 to 2.4.0.0. 
- Fix of issue #33 
Currently ltfs falis to mount LTO5 tape on LTO7 drive.  This is a basic functionality breakage. I want to fix as soon as possible.
Following tests are made
- Mount LTO5 tape on LTO7 drive as read-only mode
- Mount LTO6 tape on LTO6 drive as read-write  mode
Fixes #33

Handle read-only combination of tape and drive (#34)

---

docs/README.md
docs/com.ibm.ltfs

- Add a configuration file for syslog on macOS
The commands in this project put the messages via syslog. But almost all support OS don't put the messages by default. 
There are the configuration files put the message to /var/log/ltfs.log under doc directory for rsyslog and syslog-ng. But the ASL for mac is not existed. 

Add a file for syslog on macOS

---

src/tape_drivers/linux/sg-ibmtape/sg_scsi_tape.c

- Changes the data type of `retry_count` to unsigned integer, as we are not supposed to increment/decrement booleans.
Fixes incrementing a boolean, which is non-compliant with recent versions of the C standard.

Make retry_count an integer to avoid incrementing a boolean expression.

---

configure.ac
src/libltfs/ltfs.h

Version number is updated to 2.4.0.2 (10071) 
IBM released IBM Spectrum Archive SDE 2.4.0.2 (10071) in 2018/04/13. It is good to have a  equivalent version in this project. 

 Update version number to 2.4.0.2 (10071) 

---

src/iosched/Makefile.am
src/kmi/Makefile.am
src/tape_drivers/freebsd/cam/Makefile.am
src/tape_drivers/generic/file/Makefile.am
src/tape_drivers/generic/itdtimg/Makefile.am
src/tape_drivers/linux/lin_tape/Makefile.am
src/tape_drivers/linux/sg-ibmtape/Makefile.am
src/tape_drivers/osx/iokit-ibmtape/Makefile.am

Changes for creating rpm package cleanly.
Previously move plugin files to lib/ltfs by overwriting libdir. But this
is not a good way from creating rpm point of view. The libtool rejects
install modules to non-standard directory.
This patch make following changes
1. Once install plugin into lib directory by install-exec target
2. Remove .la files in lib directory by install-exec-hook
3. Move plugin, so files, to lib/ltfs directory ny install-exec-hook

Move plugin to lib/ltfs on install-exec-hook

---

messages/tape_linux_sg_ibmtape/root.txt
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c

Support pseudo I/O error for debugging error path for the sg backend. 
This feature is already available in the file backend and lin_tape backend.

Support pseudo error on the sg backend for debug

---

src/iosched/Makefile.am
src/kmi/Makefile.am
src/tape_drivers/generic/file/Makefile.am
src/tape_drivers/generic/itdtimg/Makefile.am
src/tape_drivers/linux/lin_tape/Makefile.am
src/tape_drivers/linux/sg-ibmtape/Makefile.am

o support autotools $(DESTDIR)
o install-hook now suport to copy compiled libraries
to a given destination directory, thus use it
for packaging tools (ubuntu, debian, arch-linux)
- support autotools $(DESTDIR)
-  install-hook now suport to copy compiled libraries
to a given destination directory, thus use it
for packaging tools (ubuntu, debian, arch-linux)
I'd like to use LTFS on Ubuntu and Arch-Linux.
I found your OpenSource project here an Github and tried to compile it on the actual LTO Release of Ubuntu (bionic). I cloaned it and build an initial debian subdir with needed build rules etc.
After some work and triggering I resolved needed dependency packages and incorporated that to the debian package build. Now it is compiling and …

ltfs: Makefile.am enhancement supporting DESTDIR

---

configure.ac
src/libltfs/Makefile.am
src/libltfs/pathname.c
src/tape_drivers/linux/sg-ibmtape/Makefile.am
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
src/tape_drivers/osx/iokit-ibmtape/Makefile.am
src/tape_drivers/osx/iokit-ibmtape/iokit_ibmtape.c

some HBAs do not return correct  transfer length and residual length.
This patch introduces the needed build-system flags to select patching the drivers for OSx and Linux.
If set, the Makefiles will include an extra preprocessor flag and compile with a workarround.

compile tape_driver with buggy I/Fs support   

---

configure.ac
src/libltfs/Makefile.am
src/libltfs/pathname.c

This pull request includes following updates:
o update autotools to make ICU version test selectable (>= v60)
o change preprocessor lable (ICU6x)
o select correct ICU unorm functions based on given preprocessor flag
Since AX_COMPARE_VERSION macro isn't available on all plattforms, i have choosen to use a simple bash string comparison. Not as flexible, but does the trick.

update ICU version handling

---

src/libltfs/ltfs_locking.h

- Fix memory leak at backtrace_info()
Currently, memory shall be leaked at backtrace_info(). Because it doesn't free the allocated memory by backtrace_symbols().

Fix memory leak at backtrace_info()

---

src/libltfs/ltfs_locking.h

Initialize funcs variable to NULL. But it shall be no effect to the functionality.

Make a tiny correction for backtrace_info()

---

src/libltfs/tape.c
src/tape_drivers/generic/file/filedebug_conf_tc.c
src/tape_drivers/generic/file/filedebug_conf_tc.h
src/tape_drivers/ibm_tape.c
src/tape_drivers/ibm_tape.h
src/tape_drivers/tape_drivers.h

Refactor the code to support new drive models and new tape types easily
Definitions for new drive models and new tape types to following files.
- src/libltfs/tape.c
- src/libltfs/tape_ops.h
- src/tape_drivers/ibm_tape.c
- src/tape_drivers/ibm_tape.h
- src/tape_drivers/tape_drivers.h

Refactor some definitions to support new models easily

---

src/libltfs/pathname.h
src/ltfs_fuse.c

Rename `pathname_nfd_normaize()` to `pathname_nfd_normalize()` in pathname.h and ltfs_fuse.c to avoid a build break in macOS.
Current source cannot be built on macOS because `pathname_nfd_normaize()` is called from `ltfs_fuse.c` (when `__APPLE__` is defined) but actually `z()` was renamed to `pathname_nfd_normalize()` in #52 . (#52 is incomplete. Only function name in the definition was changed but prototype and caller were not changed.)
I can't detect this issue when I merged the #52 because old code is installed into `/usr/local/lib` and the linker in macOS detects `pathname_nfd_normaize()` from `/usr/local/lib/libltfs.dylib`. But actually build break is there on the clean system.

Fix build break in macOS

---

src/main.c

I introduced a bug at #73 to make R/W mount at roll back mount. It shall be R/O mount.

Correction about roll back mount as R/O mount

---

src/libltfs/ltfs.c

Fix reject condition of format.
Currently LTFS over rejects format operation in the IBM enterprise tape. (Readonly format-drive combination even if cartridge-drive combination is writable with reformat)

Correct R/O handling in format

---

messages/tape_iokit_ibmtape/root.txt
messages/tape_linux_sg_ibmtape/root.txt
src/libltfs/xml_writer_libltfs.c
src/tape_drivers/freebsd/cam/cam_cmn.h
src/tape_drivers/freebsd/cam/cam_tc.c
src/tape_drivers/generic/file/filedebug_tc.c
src/tape_drivers/linux/lin_tape/lin_tape_ibmtape.c
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.h
src/tape_drivers/osx/iokit-ibmtape/iokit_ibmtape.c
src/tape_drivers/osx/iokit-ibmtape/iokit_ibmtape.h
src/tape_drivers/tape_drivers.h

Provide a complete feature to create following error condition tape.
1. Write fenced tape (set nagative value to write error trigger)
2. Write error tape (set positive value to write error trigger)
3. Read error tape (set positive value to read error trigger)
When a negative value is set to ltfs.vendor.IBM.forceErrorWrite, LTFS will clear pseudo write error condition in the following conditions.
- Load
- Unload
- Rewind
- Open
- Locate to another partition
When a positive value is set to ltfs.vendor.IBM.forceErrorWrite, LTFS will clear pseudo write error condition in the following conditions.
- Load
- Unload
- Rewind
- Open
ltfs.vendor.IBM.forceErrorRead accept only positive value. LTFS will clear pseudo read error condition in the following conditions.
- Load
- Unload
- Open
- New …

 Add a feature to create various error condition tape 

---

src/tape_drivers/freebsd/cam/cam_tc.c
src/tape_drivers/ibm_tape.h
src/tape_drivers/linux/lin_tape/lin_tape_ibmtape.c
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
src/tape_drivers/osx/iokit-ibmtape/iokit_ibmtape.c

Introduce following 2 macros to test cartridge type
- Short tape for IBM enterprise tape
- WORM tape
To reduce to add new code when new tape is added.
After this change you need to add new cartridge type only to ibm_tape.h

Introduce macros to test cartridge type

---

src/libltfs/xml_writer.c

Fix a bug of file copy logic
#82 introduces a bug to crash LTFS because of new cache file copy logic. Because it allocates 512KB buffer but it tries to read 512MB from the source file descriptor.

Fix a bug of file copy logic

---

messages/libltfs/root.txt
src/libltfs/xml_writer.c
src/libltfs/xml_writer_libltfs.c

Sync cache contents to disk before unlocking it
Sync cache contents to disk before unlocking it
- Tiny improvement  (non-breaking change)

Sync cache contents to disk before unlocking it

---

src/tape_drivers/linux/lin_tape/lin_tape_ibmtape.c
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
src/tape_drivers/osx/iokit-ibmtape/iokit_ibmtape.c

Handle an error at readpos after locate correctly
Current code returns a good when readpos after locate is successfully done even if locate is failed. This behavior is wrong. 

Handle an error at readpos after locate correctly

---

src/ltfs_fuse.c

Pass correct i-node info to the statvfs structure
statvfs::f_files shall have a count of max i-nodes
statvfs::f_ffree shall have a count of free i-nodes
The 'f_favail', 'f_fsid' and 'f_flag' fields are ignored 

Correct i-node information pass to FUSE

---

src/libltfs/xattr.c

Kick ltfs_sync by reading "ltfs.sync" VEA. In addition to reading it.
Kick ltfs_sync by reading "ltfs.sync" VEA. This behavior is useful when the tape is meta-data writable condition. In this condition, LTFS rejects to create additional file object and data. But LTFS accepts meta-data change like unlink objects, modify EA, etc.

Kick ltfs_sync() by reading ltfs.sync VEA

---

src/libltfs/ltfs.c

Return good at sync when filesystem is clean
Previously, return less space condition at sync when the tape is under less space condition.

Return good at sync when filesystem is clean

---

messages/tape_linux_sg_ibmtape/root.txt
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.h

Add a debug function to create full tape easily
For debug purpose, it is useful if we have a function to create full tape easily. 
I introduce a  ltfs.vendor.IBM.capOffset VEA to the sg backend. The sg backend shall subtruct remaining capacity from real one when this value is not 0. The unit is MB (base 1000 not 1024).

Add a debug function to create full tape easily

---

src/libltfs/tape_ops.h
src/tape_drivers/ibm_tape.c
src/tape_drivers/ibm_tape.h
src/tape_drivers/tape_drivers.h

Experimental support of the IBM TS1160 enterprise tape drive
IBM announced new enterprise tape drive TS1160. This patch is experimental support of that drive

Experimental support of the IBM TS1160 enterprise tape drive

---

messages/internal_error/root.txt
messages/tape_generic_itdtimg/root.txt
messages/tape_linux_sg_ibmtape/root.txt
src/libltfs/arch/errormap.c
src/libltfs/ltfs_error.h
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
src/tape_drivers/linux/sg-ibmtape/sg_scsi_tape.c

- Add handling when the sg driver return ENOMEM against a read or write cdb.
Following recovery procedure is executed when LTFS receives ENOMEM against a read cdb or write cdb.
0. Assume the position before issuing a command is org_pos
1. Check current position (cur_pos)
2. If cur_pos == org_pos, simply retry
3. if cur_pos == org_pos + 1, space back one record and retry
4. otherwise report error

Handle teh case the sg driver returns ENOMEM

---

messages/tape_linux_sg_ibmtape/root.txt
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c

This pull request includes following changes. 
- Try to set reserved_buffer to 1MB (But may be 512KB is reserved)
This change will reduce ENOMEM chance because 512KB buffer is reserved in a opened sg device file.
- Performance enhancement

Improve reliability of the sg backend

---

src/libltfs/xml_writer_libltfs.c

Commit some cache information before releasing lock for cache files
There is a short window to peep LTFS's internal cache information. Basically it shall be protected by an advisory lock of the index cache. But this lock is released before committing new cache files.

Commit some cache files before releasing lock for cache files

---

messages/libltfs/root.txt
src/iosched/unified.c
src/libltfs/ltfs.c
src/libltfs/tape.c
src/libltfs/xattr.c
src/tape_drivers/generic/file/filedebug_tc.c

- Handle permanent write error (WritePerm) while writing an index
+ A WritePerm happens on DP, try to write another one on DP and update MAM
+ A WritePerm happens on IP, just update MAM
Previously, a tape goes to inconsistent state, it may be recoverable, when a WritePerm happens while writing an index.
In this fix, tape state goes to R/O because of WritePerm  as same as a case WritePerm happens while writing contents of a file.

Handle write perm errors while wrinting an index

---

messages/libltfs/root.txt
src/iosched/unified.c
src/libltfs/ltfs.c
src/libltfs/tape.c
src/libltfs/xattr.c
src/tape_drivers/generic/file/filedebug_tc.c

- Handle permanent write error (WritePerm) while writing an index
+ A WritePerm happens on DP, try to write another one on DP and update MAM
+ A WritePerm happens on IP, just update MAM
This PR is for master branch of #103
Previously, a tape goes to inconsistent state, it may be recoverable, when a WritePerm happens while writing an index.
In this fix, tape state goes to R/O because of WritePerm  as same as a case WritePerm happens while writing contents of a file.

Handle write perm errors while wrinting an index (master)

---

messages/libltfs/root.txt
src/libltfs/ltfs.c
src/libltfs/xml_reader_libltfs.c
src/libltfs/xml_writer_libltfs.c

- Accept an index created by bad manner index writers
- Fix the index writer to encode '%' correctly
Previously the index writer of LTFS have a bad manner. It doesn't encode '%' correctly when it need to encode a name object by URL encode.
This behavior causes catastrophic situation when the name has both characters required URL encode like ':' and "%2f"  like "AAA%2f:BBB". 
The name "AAA%2f:BBB" is written to the index as "AAA%2f%3A". And it is read as "AAA/:" because of URL encode is required. But this name is invalid and mount is failed (inconsistent state).
The biggest problem is recovery. ltfsck skips this kind of index and finally it reverts the filesystem to the index that can be parsed. (It means data loss!!!)
- Bug fix …

Accept unexpected '/' in name

---

messages/libltfs/root.txt
src/libltfs/xml_reader_libltfs.c

This change is additional fix of #105.
Current LTFS rejects a US in name so need to escase US also as same as '/'.

Accept unexpected US (0x1f) in name

---

messages/libltfs/root.txt
src/libltfs/ltfs_internal.c
src/libltfs/xml_reader.c
src/libltfs/xml_reader_libltfs.c

- Stop seeking index when following error happens
- memory shortage
- parse error because of unexpected filename
- parse error because of non UTF-8 characters
- parse error because of too long filename
- Recover the latest index at the EOD of DP
The worst case is removing a good file in a bad index without any
warning.

Avoid to recover with prior index on parse error

---

src/tape_drivers/freebsd/cam/Makefile.am

Signed-off-by: Kevin Bowling <kevin.bowling@kev009.com>
- Fix FreeBSD automake destdir for alternate root builds
Without this fix the build fails under sandbox builds like FreeBSD's poudriere package builder.  I carry this patch locally in the ports tree until this fix can be committed and released.

Fix FreeBSD automake destdir

---

src/iosched/unified.c
src/libltfs/ltfs.c
src/libltfs/ltfs.h
src/libltfs/ltfslogging.c
src/libltfs/ltfslogging.h
src/libltfs/plugin.c
src/libltfs/plugin.h
src/libltfs/tape.c
src/libltfs/tape.h
src/libltfs/tape_ops.h
src/libltfs/xattr.c
src/libltfs/xml_reader_libltfs.c
src/libltfs/xml_writer_libltfs.c
src/main.c
src/tape_drivers/freebsd/cam/cam_tc.c
src/tape_drivers/generic/file/filedebug_tc.c
src/tape_drivers/generic/itdtimg/itdtimg_tc.c
src/tape_drivers/ibm_tape.h
src/tape_drivers/linux/lin_tape/lin_tape_ibmtape.c
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
src/tape_drivers/netbsd/scsipi-ibmtape/scsipi_ibmtape.c
src/tape_drivers/osx/iokit-ibmtape/iokit_ibmtape.c
src/utils/ltfsck.c
src/utils/mkltfs.c

This pull request includes following changes or fixes.
- Change tape backend interface to reduce differences with HPE LTFS
We support building tape backend drivers as external projects, which
lets us load HPE LTFS tape backends at run time. But since HPE tape
backend interface added a few extensions, that require some patches.
This changes reduces the differences of the tape backend interface to
make the process easier.
- Source only change

Reduce differences with HPE tape backend interface

---

src/libltfs/ltfslogging.c

Correct usage of va_start() in ltfsmsg_internal()
This warning was introduced in the previous #116. va_start() must have a provided argument at 2nd argument.

Remove warning at build

---

src/libltfs/ltfs.h

PACKAGE_NAME and PACKAGE_VERSION is removed from ltfs.h
PACKAGE_NAME and PACKAGE_VERSION is defined for makefile build of macOS but it is not a good idea to change multiple place when version number is changed.
PACKAGE_NAME and PACKAGE_VERSION shall be provided from Makefile for building macOS build.
There is no change for HomeBrew build.

Remove PACKAGE_XXX from ltfs.h

---

messages/tape_iokit_ibmtape/root.txt
messages/tape_linux_sg_ibmtape/root.txt
src/tape_drivers/ibm_tape.c
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
src/tape_drivers/osx/iokit-ibmtape/iokit_ibmtape.c

- Fix of issue #123 
Currently, WORM support in the sg backend and the iokit backend is corrupted.
Fixes #123

Support WORM tape on the sg backend and the iokit backend

---

messages/libltfs/root.txt
src/libltfs/ltfs.c
src/libltfs/ltfs_internal.c
src/libltfs/xml_writer.c

- Keep trying to acquire advisory lock in 20 min
- LTFS forcely writes down an index when the lock cannot be acquired
- Fix a few message errors
Linux kernel returns EDEADLK against taking advisory lock even if 2 threads try to acquire advisory locks in each thread individually. So LTFS may need to retry acquiring to capture an advisory lock even if the kernel returns EDEADLK.

Handle EDEADLK error for acquiring advisory lock

---

messages/tape_linux_sg_ibmtape/root.txt
src/tape_drivers/linux/sg-ibmtape/sg_scsi_tape.c

Print a log when unknown sense is received from the drive for drive
investigation.
Now, the ltfs doesn't log any message when drive returns an unknown sense. The unknown sense means that sense is not listed into sense-error_code conversion table in ltfs.
So user doesn't detect which error is returned from the device. It is very hard to investigate the roor cause.

Add a log when unknown sense is received

---

configure.ac

Compiler will stop when it finds an warning if the option is enabled.
Disable is default behavior.
This a nice function for writing safety code.

Support --enable-warning-as-error option to build

---

docs/ltfs-log.conf

With rsyslog as a logger, /var/log/messages won't contain LTFS log anymore.
Now only the /var/log/ltfs.log is a log file for LTFS.
New ltfs-log.conf for rsyslog works for rsyslog7 and later.

Do not log into /var/log/messages

---

messages/internal_error/root.txt
src/libltfs/arch/errormap.c
src/libltfs/ltfs_error.h
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
src/tape_drivers/linux/sg-ibmtape/sg_scsi_tape.c

- Return connection lost error code when LTFS detects a drive connection lost
Return connection lost error to handle this case correctly by the caller

Handle drive connection lost

---

conf/Makefile.am

This fixes a failure when building a Debian package in a chroot, for example, when the $(sysconfdir) doesn't already exist.

Ensure $(sysconfdir) exists before installing a file to it

---

src/utils/Makefile.am
src/utils/ltfsoacp

- Add order aware copy utility for LTFS
- Fix of issue #138 
- command is `bin/ltfsoacp`
- written by python2.7
- options are subset of GNU cp except --keep-tree
- `ltfsoacp` accepts source list from stdin instead of arguments
examples:
```
$ ltfsoacp /foo/aaa /foo/bbb
$ ltfsoacp /foo/aaa /foo/bbb /bar
$ ltfsoacp /foo/ddd /foo/DDD /bar
$ find /foo/ddd -type f | ltfsoacp -t /bar
$ find /foo/ddd -type d -maxdepth 1 | ltfsoacp -t /bar
$ find /foo/ddd -type f | ltfsoacp -t /bar --keep-tree=/foo/ddd
```
Fixes #138 

Add order aware copy utility for LTFS

---

src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c

Calculate read length from req.residm in _cdb_read()
- Fix of issue #140 
When READ6 is issued with sili the sg backend returns a wrong length.
This behavior doesn't create any error when LBP is disabled (default),
but LBP is enabled by `-o scsi_lbprotection=on` is specified in the
argument. The sg backend returns CRC error because wrong read length is
returned from _cdb_read().
The problem is the sg backend returns req.dxfer_len even if sili is
true. This field is [I] in the document so we must not expect the field
is updated in SG_IO ioctl. We must use req.resid instead.
Fixes #140 

Fix the bug of detecting read length

---

src/libltfs/tape.c
src/libltfs/tape.h
src/libltfs/tape_ops.h
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
src/tape_drivers/osx/iokit-ibmtape/iokit_ibmtape.c

There are a few minor change in this change
- Change return code of modesense method
- Support drives that doesn't support PEW and append only mode
- Set unit in GB into partition mode page to format a tape 
- Code cleaning
It's not a feature enhancement but I made some minor change.

Set PF bit in modesense

---

man/sgml/ltfs-sde.sgml

- fix tiny error in the SGML source for man page (missing dash before `-o`)

fix error in man

---

src/libltfs/pathname.c

Fix parse error because of symlink target is too long
- Fix of issue #148
The index parser reports error when symlink target length is 256 or more. This change remove the length check of symlink target
Fixes #148

Fix parse error because of symlink target is too long

---

src/utils/ltfs_ordered_copy

- Fix of issue #155 
1. `cp -p` copies mode,ownership and timestamps; `cp -a` copies all the attributes including mode,ownership,timestamps,context, links, xattr(according to man page) 
2. `shutil.copy()` copies mode(permission bits)
3. `shutil.copy2()` copies mode, last access time, last modification time, and flags 
4. Neither `shutil.copy()` nor `shutil.copy2()` can copy xattr and ownership
5. Now ,`ltfs_ordered_copy -a` can copy mode,timestamps and xattr , which is slightly different from `cp -a` because ownership and links are not considered
6. Now , `ltfs_ordered_copy -p` can copy mode and timestamps which is slightly different from `cp -p` because ownership and links are not considered
######
|   | `shutil.copy()` | …

ltfs_ordered_copy improvement

---

README.md

The bug affecting the ICU package in Debian 9 has now been fixed and LTFS can
now be built successfully there.

Update README to reflect that LTFS builds sucessfully on Debian 9.10

---

src/libltfs/pathname.c

Allow `BOM` in the path name
- Fix of issue #159 
In the previous version (2.2), LTFS allows BOM in the path name. But new
code rejects it. May be it is a kind of side effect of the changes for
'%' support in the path name. So I will revert the implementation.
Fixes #159

Allow BOM in the path name

---

src/tape_drivers/linux/sg-ibmtape/Makefile.am
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
src/tape_drivers/open_factor.c
src/tape_drivers/open_factor.h

Added the HBA load balancing feature. 
Added the HBA load balancing feature. But this feature is effective only when one LTFS instance uses multiple drives. In other words, this feature doesn't balance the HBA work load for one drive. Once a drive is opened through the sg backend same path will be used continuously.  And path may be switched when opened path is down an any reason.

Support HBA load balancing

---

messages/tape_linux_sg_ibmtape/root.txt
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c

Keep searching the device to open even if reserving the device fails when drive serial is specified in the sg  backend.
This is a fix of side effect of specification change.

Check the reservation in sg_ibmtape_open()

---

src/tape_drivers/ibm_tape.c
src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
src/tape_drivers/linux/sg-ibmtape/sg_scsi_tape.c

Treat DID_NEXUS_FAILURE as reservation conflict.
In the kernel 4.14 on Power9, scsi middle layer seems to return DID_NEXUS_FAILURE(0x11) in host_status. This change handle this behavior. Of cause, SCSI_RESERVATION_CONFLICT in masked status is treated as reservation conflict. 
In addition to DID_NEXUS_FAILURE handling. I slightly change the code about timeout table handling. It is configured after open the device by serial number search.

Treat DID_NEXUS_FAILURE as reservation conflict

---

src/libltfs/tape.c

This pull request fixes the problem to miss the physical write protected notch condition
By the backend I/F change, `device_data::write_protected` shall have an integer value about physical write protect condition. But it still has a boolean value. 
This shall be corrected.

Fix the problem to miss the write protect notch condition

---

src/tape_drivers/generic/file/filedebug_tc.c

In filedebug_open(), devname is used in a situation where it is not
necessarily non-NULL.  If it is NULL, strdup the passed in name.
- Fixes a NULL pointer dereference in the file backend.

Fix a NULL pointer dereference in the file backend.

---

src/libltfs/xml.h
src/libltfs/xml_reader_libltfs.c

Accept `<name></name>` for root directory.
Name of `root` directory is treated as a volume name. So `empty` value is allowed when there is no volume name.
The current code only accepts `<name/>` as empty tag. So the index parser may reject an index written by another implementation.
This fix accepts both `<name/>` and `<name></name>`

Relax the index parser to allow 0-byte name

---

src/tape_drivers/linux/sg-ibmtape/sg_scsi_tape.h

Previously the code set SG_FLAG_LUN_INHIBIT when LTFS issues SG_IO.
But this flag is not effective to any FC/SAS devices anymore. So it is unset in this change.
- Small correction

Correct flags on sg_io_hdr

---

src/libltfs/tape.c

Treat cleaning required sense as a good state against unload command.
- Fix of issue #190
Cleaning required sense is an informational sense from drive point of view. So we need to ignore that.

Ignore cleaning required sense from drive.

---

src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
src/tape_drivers/netbsd/scsipi-ibmtape/scsipi_ibmtape.c
src/tape_drivers/osx/iokit-ibmtape/iokit_ibmtape.c

This change checks generation of LTO drive and use CRC32C if the drive
is LTO-7 or LTO-8. The x86_64 CPU has H/W accelerator for CRC32C. So
faster process and lower CPU power can be expected.
- Fix of issue #194
Currently LTFS uses Reed-Solomon for logical block protection on LTO
drive. But there is no H/W accelerator for Reed-Solomon. So more CPU
power is needed than CRC32C when `-o scsi_lbprotect=on` on LTO drive.
Fixes #194

Use CRC32C as much as possible on LTO

---

src/tape_drivers/freebsd/cam/cam_cmn.c
src/tape_drivers/linux/sg/sg_scsi_tape.c
src/tape_drivers/netbsd/scsipi-ibmtape/scsipi_scsi_tape.c
src/tape_drivers/osx/iokit/iokit_scsi.c
src/tape_drivers/vendor_compat.c

Handle unknown H/W as a H/W correctly
At this time, unknown H/W error is detected as just an unknown error. But actually, drive might not work correctly at all at this timing. So it is good to handle it as a H/W error.

Handle unknown H/W as a H/W correctly

---

.github/workflows/build-ubuntu-focal.yml
README.md

State HP drive support in README
Following changes are made by this PR.
1. Add HP's drives into README as supported drives
2. Add build checker for Ubuntu 20.04 LTS (Focal)

State HP drive support in README

---

src/tape_drivers/freebsd/cam/Makefile.am
src/tape_drivers/linux/lin_tape/Makefile.am
src/tape_drivers/linux/sg/Makefile.am
src/tape_drivers/linux/sg/quantum_tape.c
src/tape_drivers/netbsd/scsipi-ibmtape/Makefile.am
src/tape_drivers/osx/iokit/Makefile.am
src/tape_drivers/quantum_tape.c
src/tape_drivers/quantum_tape.h
src/tape_drivers/tape_drivers.h
src/tape_drivers/vendor_compat.c

Very experimental support of Quantum LTO HH drives
I would like to add the Quantum LTO HH drives to support list using multi-vendor drive support framework. Actually I don't have any Quantum drives but I believe this change works fine if Quantum LTO HH drives has almost same behavior as IBM LTO HH drive.
Actually I don't know its is almost same or not. So I also would like to ask Quantum drive users to confirm the behavior.

Very experimental support of Quantum LTO HH drives

---

messages/libltfs/root.txt
src/libltfs/ltfs.c
src/libltfs/ltfs.h

Currently, LTFS might try to write an index on tape even if the tape is marked as "Write Error tape" when index info and volume lock info is different on MAM.
This fix introduce following changes
1. Print more MAM info when volume lock is specified
2. Print a warning message and capture dump when index info and volume
lock info is different on an error tape mount
3. Skip to write index at unmount when LTFS make a error tape mount

Handle dirty MAM on unmount

---

messages/libltfs/root.txt
src/libltfs/tape.c
src/tape_drivers/osx/iokit/.gitignore

Skip to set append only mode when the drive returns error at setting append only mode.
- Fix of issue #212 
For now,  just ignore the error (-EDEV_ILLEGAL_REQUEST) from drive against `modeselect` command while setting append only mode. 
We might need to consider to skip to set append only mode cleanly within the backend if required. (At this time HP's LTO5 doesn't support it.)
Fixes #212 

Handle error on setting append only mode

---

messages/libltfs/root.txt
src/libltfs/ltfs.c
src/libltfs/xml_reader_libltfs.c

LTFS capture drive dump when it detects funny MAM at mount. This code was introduced into PR #210. But we find a condition to make a funny MAM. So remove the code to capture drive dump at that situation.
In the MAM condition below, LTFS capture drive dump now.
1. MAM shows write perm at DP
2. MAM shows index on DP is the newest (IP shall be the newest)
This situation would happen when some non-medium error happens on IP in
the process of medium error on DP.
Please include relevant motivation and context. List any dependencies that are required for this change.
In addition to logic changes, message cleaning is done in this PR.

Do not capture dump when LTFS detects funny MAM

---

src/libltfs/ltfs.c
src/libltfs/xml_writer_libltfs.c

This commit fixes the case about cache handling when a write error happens at writing following FM of an index.
Previous code might propagate files to be synced even if last index would be partial. Because WRITEFM command against the following FM of index means drive can't flush the buffered data completely. So the files only in the last index would lost at next mount.
Move the WRITEFM command handling to xml_schema_to_tape(). And propagate the caches when the command is successfully done.

Fix handling when caches is available

---

src/utils/ltfs_ordered_copy

There are 2 changes on `ltfs-ordered_copy`
1. Change python interpreter from python 2.7 to system default
2. Fix NonType error

Tiny corrction of value initalize

---

README.md

Add Quantum HH drives in the support list. And also add the descriptions about buggy HBAs.
Fixes issue #219 
- Document

Add Quantum HH drives in the support list

---

src/utils/ltfs_ordered_copy

Fix disk to disk  copy reporting on ltfs_ordered_copy
Success counter is always 0 at disk to disk copy because pass the immutable object to writer thread.

Fix DtoD copy reporting on ltfs_ordered_copy

---

src/libltfs/fs.c
src/tape_drivers/freebsd/cam/Makefile.am

Fix build break on FreeBSD.
Previous `Makefile.am` tries to link a same object file twice. So linker reports a multiple objects error.

Fix build break in FreeBSD

---

messages/internal_error/root.txt
messages/libltfs/root.txt
src/libltfs/arch/errormap.c
src/libltfs/ltfs_error.h
src/libltfs/tape.c

Override the error code to `LTFS_LOCATE_ERROR` when tape backend's `locate()` call returns write-perm error.
On #232, LTFS could remove files automatically when tape backend's `locate()` call returns write-perm error even if It is not necessary. But I believe this is so rare like breaking H/W.
Fixes #232

Handle write-perm on LOCATE correctly

---

src/utils/ltfs_ordered_copy

- Fix of issue #236 
This changes the behavior of ltfs_ordered_copy when xattr is not supported on the destination filesystem. Instead of failing the copy, it disables the `-p` flag and continues on without attempting to preserve attributes. Previously, users would be unable to copy to a non-ltfs filesystem that does not support xattr. Now, users can still perform the copy, but without the additional metadata added by `-p`.
Fixes #236 
- This change migth require a documentation update

Treat errno 95 as non-ltfs destination (Fix #236)

---

src/utils/ltfs_ordered_copy

- Add `--keep-tree` support for single file copies
Single file copies did not honor the `--keep-tree` flag so would always end up in the destination folder regardless of tree depth of source. This changes makes it possible to copy a single file with the tree preserved. It reuses the same logic that is used for multi-file copies.

ltfs_ordered_copy: honor `--keep-tree` for single file copies

---

messages/tape_iokit/root.txt
src/tape_drivers/freebsd/cam/cam_tc.c
src/tape_drivers/linux/sg/sg_tape.c
src/tape_drivers/osx/iokit/iokit_tape.c
src/tape_drivers/quantum_tape.c

Support another Quantum drive `'QUANTUM ' / 'ULTRIUM 5       '`
- Fix of issue #245
It looks Quantum has 2 types of LTO5 drive. One is `QUANTUM/ULTRIUM 5` the other is `QUANTUM/ULTRIUM-HH5`. `QUANTUM/ULTRIUM 5` is supported into this PR.
Fixes #245 

Support another Quantum drive

---

src/tape_drivers/freebsd/cam/cam_tc.c
src/tape_drivers/linux/sg/sg_tape.c
src/tape_drivers/osx/iokit/iokit_tape.c

Fix how to get remaining capacity on HP LTO6.
- Fix of issue #241 
It looks HP LTO6 doesn't support LP17h. So this fix uses LP31h instead like IBM/HP LTO5.
Fixes #241 

Fix remaining capacity handling of HP LTO6

---

src/libltfs/ltfs.c
src/libltfs/ltfs.h
src/libltfs/tape.c
src/libltfs/tape.h
src/libltfs/tape_ops.h
src/libltfs/xattr.c
src/tape_drivers/freebsd/cam/cam_tc.c
src/tape_drivers/generic/file/filedebug_tc.c
src/tape_drivers/generic/itdtimg/itdtimg_tc.c
src/tape_drivers/linux/lin_tape/lin_tape_ibmtape.c
src/tape_drivers/linux/sg/sg_tape.c
src/tape_drivers/netbsd/scsipi-ibmtape/scsipi_ibmtape.c
src/tape_drivers/osx/iokit/iokit_tape.c
src/tape_drivers/tape_drivers.h

Introduce generic logselect issue I/F via EA by `ltfs.vendor.IBM.logPage.XX.YY`.
XX shall be a hex value like `A0` as page code. YY XX shall be a hex value like `60` as subpage code.
Once LTFS receives a correct VEA, XX and YY can be converted by `strroul()` with `base=16`, LTFS always issues logsense to the drive and return the specified page by binary.

Introduce generic logselect issue I/F via EA

---

src/tape_drivers/quantum_tape.c

Experimental support of another quantum LTO6 drive.
- Fix of issue #257 
Just add the Quantum's `ULTRIUM 6` drive into the list.
Fixes #257

Add  another quantum LTO6 into the list

---

src/tape_drivers/generic/itdtimg/itdtimg_tc.c

Fix plugin load error of `itdtimg` reported by #255.
- Fix of issue #255
It looks function table is incomplete. So I made a tiny fix.
Fixes #255
-

Fix plugin load error for itdtimg

---

src/libltfs/ltfs.c
src/libltfs/ltfs.h
src/libltfs/tape.c
src/libltfs/tape.h
src/libltfs/tape_ops.h
src/libltfs/xattr.c
src/tape_drivers/freebsd/cam/cam_tc.c
src/tape_drivers/linux/lin_tape/lin_tape_ibmtape.c
src/tape_drivers/linux/sg/sg_tape.c
src/tape_drivers/netbsd/scsipi-ibmtape/scsipi_ibmtape.c
src/tape_drivers/osx/iokit/iokit_tape.c
src/tape_drivers/tape_drivers.h

Introduce generic MAM fields capture I/F via `ltfs.vendor.IBM.mediaMAM.XX`.
XX shall be one of `00`,  `01` , `IP` or `DP`.
- Fix of issue #256
The new introduced VEA returns the MAM value by binary. You need to parse it by yourself.
Fixes #256

Introduce generic MAM fields capture I/F

---

src/tape_drivers/quantum_tape.c

Fix the drive type of Quantum LTO6 drive.
Fix of issue #265. (Fixes #265)

Fix the drive type of Quantum LTO6

---

configure.ac
src/libltfs/arch/arch_info.c

- Fix of issue #262 
At this time, `autogen.sh` fails on newer automake/autoconf. This change resolves it. I checked the change on RHEL7 (x86_64) and RHEL8 (x86_64).
Fixes #262

Remove AC_CONFIG_MACRO_DIR from configure.ac

---

src/libltfs/plugin.c

- Wipe plugin structure before loading a plugin.
- Fix segfault when unloading plugins with no messages
This is a general solution to a specific problem I encountered, where a segfault is raised when a plugin is unloaded, if it does not provide icu messages, because the pointer is non-null.

Wipe the plugin structure before loading a plugin.

---

src/tape_drivers/vendor_compat.c

Fix of #298 (f0575354f60839c1cc0f2774aae8dc41af85b514)
Change to correct vendor ID length to each vendors.

Correct compare length of vendor IDs

---

messages/libltfs/root.txt
src/libltfs/ltfs.c

Scan the tape for searching the latest index when VCR is unmatched for mounting write permed tape.
- Fix of issue #302 
Do not trust MAM and searching the latest index when VCR reported by the drive and VCR in MAM is unmatched.
Fixes #302

Handle unupdated MAM tape at write perm

---

configure.ac

This fixes building LTFS on Debian 11.

Fix fallback to pkg-config when icu-config missing

---

src/libltfs/ltfs_internal.c

Alter ltfs_check_medium to do a more thorough detection of the state of
the partitions after the detected indices and set the eod/append
position appropriately if the partition ends in data + filemark
Fixes #272

Correct ltfs_check_medium handling of partitions ending in data+fm

---

src/libltfs/ltfs.c

Set negative value correctly when sync failure happens.
- Additional fix of issue #315 (#316)
Currently error code of the sync failure is not correct (return a positive value). But it is wrong, need to return negative value.

Tiny correction for sync fail

---

src/libltfs/ltfs_fsops.c
src/libltfs/xattr.c
src/libltfs/xattr.h

Support `ltfs.hash.*` EAs introduced into the LTFS format spec 2.4.
- Fix of issue #297
This commit also includes the refactoring about xattr.c.
Fixes #297

Support `ltfs.hash.*` EAs

---

configure.ac

- Fix of issue #328
The option `-ldl` shall set to the linker option anytime because it is required for loading backend. So we don't expect to be set it by other library's option configuration.
Fixes #328

Fix link failure in Debian11

---

src/ltfs_fuse.c

Do not take for granted that __WORDSIZE is defined to distinguish between 32 and 64 bit platforms. If undefined on LP64 machine, STRUCT_TO_FILEHANDLE corrupts the filehande.
Instead use ULONG_MAX from <limits.h> which is mandated by ISO C99.

Fix filehandle corruption on LP64

---

src/tape_drivers/linux/sg/sg_tape.c

Return an error without issuing GRAO command in LTO9-HH. 
LTO9-HH doesn't support RAO feature. At this time, LTFS issues GRAO command even if the drive is LTO9-HH and receive an invalid CDB error. As a result, LTFS captures a drive dump.
Fixes #347

Return an error without issuing GRAO command in LTO9-HH

---

.github/workflows/build-centos7.yml
.github/workflows/build-centos8.yml
messages/iosched_unified/root.txt
messages/libltfs/root.txt
src/iosched/unified.c
src/libltfs/ltfs_fsops_raw.c
src/libltfs/tape.c
src/libltfs/tape.h
src/libltfs/tape_ops.h
src/tape_drivers/freebsd/cam/cam_tc.c
src/tape_drivers/generic/file/filedebug_tc.c
src/tape_drivers/generic/itdtimg/itdtimg_tc.c
src/tape_drivers/linux/lin_tape/lin_tape_ibmtape.c
src/tape_drivers/linux/sg/sg_tape.c
src/tape_drivers/netbsd/scsipi-ibmtape/scsipi_ibmtape.c
src/tape_drivers/osx/iokit/iokit_tape.c
src/tape_drivers/tape_drivers.h

- Fix of issue #36
- Changes backend interface for handling write perm
- Previously, it returns number of records in the drive buffer. Currently, it returns first untransferred record position to tape (In other words written but not transferred to tape yet) and it is used as error position
- Consider the final index on the partition as error position even if very small number is returned (this is a safeguard to avoid over kill of extents)
Fixes #36
--- 
Test Log
```
On Linux
3135 LTFS11031I Volume mounted successfully. NO_BARCODE : Gen = 2 / (a, 5) -> (b, 8008) / 00013B0119.
3135 LTFS14111I Initial setup completed successfully.
3135 LTFS14112I Invoke 'mount' command to check the …
```

Improve error position detention at WRITE PERM

---

src/Makefile.am
src/iosched/Makefile.am
src/kmi/Makefile.am
src/libltfs/Makefile.am
src/tape_drivers/freebsd/cam/Makefile.am
src/tape_drivers/generic/file/Makefile.am
src/tape_drivers/generic/itdtimg/Makefile.am
src/tape_drivers/linux/lin_tape/Makefile.am
src/tape_drivers/linux/sg/Makefile.am
src/tape_drivers/netbsd/scsipi-ibmtape/Makefile.am
src/tape_drivers/osx/iokit/Makefile.am
src/utils/Makefile.am

Current linker flag for creating shared libraries are not good. The linker called from libtool reports errors of unexisted files.
This modifications fixes  linking problem from 3rd party apps which links the shared libraries provided from LTFS.
Do not link the message bundles with `-l` options. But specify the object files directly.

Modify linker flags

---

src/utils/ltfs_ordered_copy

There is type mismatch into detecting the code that destination is LTFS or not. The xattr module returns binary data (without NULL termination) so binary compare is required.
This change also includes a bug fix at single file copy. It tries to get a length of `None` type object.
- Fix of issue #370
Fixes #370 

Fix a type mismatch bug in ltfs_ordered_copy

---

configure.ac

bug adding extra parameters " 2> /dev/null"  to the gcc command line,
- Fix of issue #374

fix gcc error msg display

---

build.sh
configure.ac

Replace icu-config with pkg-config， icu-config is no longer needed.

fix icu-config,  and  package libicu66 cannot be found in Debian10/debian11

---

src/tape_drivers/freebsd/cam/cam_tc.c

IBM drives do not check PF bit in mode select (from what I see in the document SCSI Reference for IBM LTO Ultrium Tape Drive), but HP drives want it set (at least my HP Ultrium 3000 did not work when PF bit was 0).
The Linux driver is already setting the PF bit in sg_modeselect, but for some reason the CAM driver for FreeBSD noes not set it in camtape_modeselect.
Before this change, I was unable to format nor mount when using my HP drive on FreeBSD:
`
LTFS31213I Error on modeselect: (pass8:mps0:0:6:0): MODE SELECT(10). CDB: 55 00 00 00 00 00 00 00 30 00
(pass8:mps0:0:6:0): CAM status: SCSI Status Error
(pass8:mps0:0:6:0): SCSI status: Check Condition
(pass8:mps0:0:6:0): SCSI sense: ILLEGAL REQUEST asc:24,0 (Invalid field in CDB)
(pass8:mps0:0:6:0): Command byte 1 bit 4 is invalid
`
After …

Make it work for HP Ultrium 3000 on FreeBSD

---

src/Makefile.am

- Fix of issue #385 
Install a few headers (`xml.h` and `arch/errormap.h`) of the libltfs for using teh libltfs library with dynamic link.
Fixes #385 

Install a few more headers by `make install`

---

messages/print_error_messages.py
messages/tape_linux_sg/root.txt
src/tape_drivers/linux/sg/sg_tape.c

- Fix of issue #409 
Try to fetch the stable (3 straight same response) from the drive for detecting the new path for failover is as same as previous path or not.
Fixes #409 
- Especially this change is a kind of workaround, LTFS doesn't expects one-shot false `good` response from the drive at all

Handle one-shot false `good` against TUR at failover process 

---

src/utils/ltfs_ordered_copy

- Do not hardcore errno numbers in ltfs_ordered_copy because those are system-dependent. Python has an errno module in its standard library which provides the correct numbers on each platform. I've also put a helper function to check for errno because some may not be present (some systems use ENODATA but other systems do not have it defined and instead use ENOATTR).
- Use methods like getxattr instead of get. The pyxattr library obsoleted those, but by now these are still available, and some systems like FreeBSD use the xattr library which do not have the get method. If, in the future, pyxattr library removes these methods, we could do something like if not hasattr(xattr, 'getxattr'): xattr.getxattr = xattr.get, but by now I think we're fine.

Add support for FreeBSD to ltfs_ordered_copy

---

messages/bin_ltfs/root.txt
src/main.c

- Fix of issue #403 
- Added warning message when fuse main function returns an error code.
This change is needed to be able to track an error on fuse_main in case it happens. 
Fixes #403 
- New feature: Addition of warning message to show error code returned by fuse_main function.

Fuse main log addition

---

src/tape_drivers/linux/lin_tape/lin_tape_ibmtape.c

This pull request includes one bugfix.
This is a very simple fix.  The bug is pretty obvious. It causes all LTFS tape mounts to fail on our new Rocky Linux 8 machine using the lin_tape driver, with a log output like this:
```
c134 LTFS17089I Distribution: Rocky Linux release 8.7 (Green Obsidian).
c134 LTFS17089I Distribution: Rocky Linux release 8.7 (Green Obsidian).
c134 LTFS17089I Distribution: Rocky Linux release 8.7 (Green Obsidian).
c134 LTFS14064I Sync type is "unmount".
c134 LTFS17085I Plugin: Loading "lin_tape" tape backend.
c134 LTFS17085I Plugin: Loading "unified" iosched backend.
c134 LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
c134 LTFS30416I lin_tape version is 3.0.64.
c134 LTFS30423I Opening a device through ibmtape driver …
```

bugfix: cannot mount LTFS tapes under Rocky Linux with lin_tape driver

---

src/libltfs/xattr.c

This pull request includes a fix for the following problem: attempting to read the extended attribute "ltfs.mediaPool.name" will fail with an LTFS_NO_XATTR error:
```
rgoedeken@fk-rg-03 TapeTools % xattr -p ltfs.mediaPool.name /Volumes/tape000002
xattr: /Volumes/tape000002: No such xattr: ltfs.mediaPool.name
```
Previously, this attribute could be written via some special-case code in xattr_set(), and presumably it was designed this way so that the attribute's value could be stored in the LTFS index. But this appears to be unnecessary as I don't see anywhere that this value gets written to the XML index.
Previously, this attribute could not be read at all, and any attempt would fail with LTFS_NO_XATTR. With this change, it can be read as well as written, as it is treated like all other …

Treat extended attribute ltfs.mediaPool.name like a virtual extended attribute. Allow both reading and writing, and store in MAM data.

---

messages/bin_ltfs/root.txt
src/main.c

- Fix of issue #403 
- Added warning message when fuse main function returns an error code.
This change is needed to be able to track an error on fuse_main in case it happens.  This PR is to apply the change to v2.4-stable change. 
Fixes #403 
- New feature: Addition of warning message to show error code returned by fuse_main function.

Fuse main log addition to v2.4 stable branch

---

src/libltfs/tape.c

Free the buffer for fetching MAM correctly.
- Fix of issue #414
Fix a memory leak found by `valgrind`.
Fixes #414

Fix a memory leak at `tape_read_attr()`

---

src/libltfs/tape_ops.h
src/tape_drivers/generic/file/filedebug_tc.c
src/tape_drivers/ibm_tape.c
src/tape_drivers/tape_drivers.h

This pull request includes following changes
- JF Tape support
- TS1170 Drive support
Includes:
- Jag7 plain and encrypted density codes
- JF Tape table timeout
- TS1170 drive compatibility with JF tapes, and backwards compatibility with JE, JV and JM tapes.

Linux Jaguar 7 Tape and TS1170 Drive Support

---

src/tape_drivers/freebsd/cam/cam_tc.c

Add a missed semicolon that prevents compilation on FreeBSD

freebsd: add missing semicolon in cam_tc

---

src/libltfs/ltfstrace.c

The problem was found by code scan. Use delete safe iteration instead.
- Fix of issue #457 
The CodeQL on the GitHub found three `potential use after free` issues. All are same flavor, it 
means, use a pointer after free. So change the logic from normal iteration to delete safe iteration.
This fix might be good to merge to the `v2.4-stable` branch also.
Fixes #457

Fix potential use after free issues

---

src/iosched/unified.c
src/libltfs/ltfs.c
src/libltfs/ltfs.h
src/libltfs/ltfs_fsops.c
src/libltfs/ltfs_internal.c
src/libltfs/periodic_sync.c
src/libltfs/xattr.c
src/ltfs_fuse.c
src/utils/ltfsck.c

In the LTFS format spec 2.5, behavior of sync is changed. 
- Sync index when `ltfs.commitMessage` is written
- Sync index with a written message as a commit message via `ltfs.sync` 
The changes in this PR make commit massage more specific. It means specified message is always written down to the tape. So there is no need to take care about carry over of the message.
In this PR, I made the changes below.
1. `commit message` is always specified implicitly or explicitly
2. In the implicit case, like periodic, unmount etc., the message is automatically generated based on the reason of `sync`
Fixes #455 

Change the `sync` behavior to fit the LTFS format Spec 2.5

---

configure.ac
contrib/ut-incindex/README.md
contrib/ut-incindex/ut-basic.sh
contrib/ut-incindex/utils.sh
messages/internal_error/root.txt
messages/libltfs/root.txt
src/iosched/unified.c
src/libltfs/arch/errormap.c
src/libltfs/inc_journal.c
src/libltfs/inc_journal.h
src/libltfs/ltfs.c
src/libltfs/ltfs.h
src/libltfs/ltfs_error.h
src/libltfs/ltfs_fsops.c
src/libltfs/ltfs_internal.c
src/libltfs/periodic_sync.c
src/libltfs/xattr.c
src/libltfs/xml_libltfs.h
src/libltfs/xml_writer_libltfs.c
src/ltfs_fuse.c
src/utils/ltfsck.c

Introduce incremental index writing feature by XML. 
- Generate an incremental index via VEA `ltfs.vendor.IBM.IncrementalSync`
- This feature is kicked only from VEA at this time
- Need to enable `--enable-format-spec25` to the `configure` script
- Introduce `--enable-xml-indent` option to the `configure` script for better XML debug
- Introduce unit test scripts under `contrib/ut-incindex`
Fixes #452 

Introduce incremental index write down in XML format

---

src/libltfs/ltfs.c

- Fix issue #479
- Changed flags for `_ltfs_search_index_wp`
When a tape cartridge with a write permanent error is trying to be mounted and the MAM (cartridge memory) attribute of the Index Partion (IP) stores a generation number **different** than the MAM attribute of the Data Partition (DP), the mount process fails even when ltfs can still search for the index in the other partition. 
The code that belongs to the logic that handles WP happens on IP, defined "can_skip_ip" flag as false and it shall be **true**. On the other hand, the code that handles WP happens on DP, defined the "can_skip_ip" as true and it should be false. The logic is now adjusted. 

Changed skip flags when calling _ltfs_search_index_wp

---

src/utils/ltfs_ordered_copy

ltfs_ordered_copy now sorts files in the correct order before copying
The os.walkdir generator in use by ltfs_ordered_copy uses os.listdir - which returns path names in an arbitrary order. Effectively copying files to tape in a completely random order. This simple change resolves this problem by sorting listed paths.
Expected result:
```
Tape order aware copy for LTFS
Destination /mnt/ltfs/20_04_2025 is LTFS
On disk sources: 9
Source tapes: 0
Copying on 9 disk files with 1 threads
"/home/ubuntu/ltfs_cache/Photos/Photos.7z.001" -> "/mnt/ltfs/20_04_2025/Photos/Photos.7z.001"
"/home/ubuntu/ltfs_cache/Photos/Photos.7z.002" -> "/mnt/ltfs/20_04_2025/Photos/Photos.7z.002"
"/home/ubuntu/ltfs_cache/Photos/Photos.7z.003" -> "/mnt/ltfs/20_04_2025/Photos/Photos.7z.003" …
```

ltfs_ordered_copy now sorts files in the correct order before copying

---

validate_error_messages.py

Updated scripts that did not work with python 3.
Updated scripts that did not work with python 3, all of our python scripts work with python 3 except for the one updated in this commit, we do not even ask for python2 to be installed for the product to work.
- Refactoring

update: validate_error_messages.py to work using python3

---

messages/bin_ltfsck/root.txt
messages/bin_mkltfs/root.txt
src/libltfs/arch/arch_info.h
src/main.c
src/utils/ltfsck.c
src/utils/mkltfs.c

GCC `__VERSION__ ` Macro is undefined on the new compilation process in windows, causing crash in binaries
Fixes #534 

Set NA to GCC Version in Windows
