LinearTapeFileSystem/ltfs

src/libltfs/tape.c, src/libltfs/tape_ops.h, src/tape_drivers/ibm_tape.c
M8 support is announced. So provide this feature in advance. This feature is not tested well. Additional tests will be performed and additional fix will be introduced in the future.
=> Experimental support of M8 cartridge

src/libltfs/ltfs.h, src/tape_drivers/ibm_tape.c
- Remove needless spaces from device type names
- Cleanup PACKAGE VERSION definition for building package by plain
makefile in macOS
Just a cleaning of sources
=> Cleaning definitions

src/tape_drivers/generic/file/filedebug_tc.c
This pull requests updates a debug message and improves comments in filedebug_tc.
This pull requests updates a debug message and improves comments in filedebug_tc.
Debug message + update to comments.
=> Improve comments and error message on allocation error

src/libltfs/xml_writer_libltfs.c
- Add consumed block for each files into the offset cache
=> Add consumed block for each files into the offset cache

src/tape_drivers/generic/file/filedebug_tc.c, src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c, src/tape_drivers/osx/iokit-ibmtape/iokit_ibmtape.c
Two fixes for the backends.
1. Product name handling in the file backend
2. Correct density code and cartridge type reporting for the sg and the iokit backend
These are tiny corrections.
=> Backend fixes

src/libltfs/pathname.c
- Fix of issue #58 
Fixes issue #58
=> Fix the build break on non-ICU6x system

src/libltfs/ltfs_locking.h
Fix memory leak at backtrace_info().
The change is quite same as #61 and #62.
=> Fix memory leak at backtrace_info()

configure.ac
Modify version number for next release to distinguish between current version.
Currently version number in master branch is as same as when the last stable branch is created. I believe it is not a good choice because multiple codes can have a same version.
New policy is increment the version number when a stable branch is created.
=> Modify version number for next release

messages/make_message_src.sh
Handle windows to make message bundle (Experimental)
- Experimental change
=> Modify make_message_src.sh to handle windows

src/libltfs/ltfs.h
Correct package version in ltfs.h
=> Correct package version in ltfs.h

messages/internal_error/root.txt, src/libltfs/arch/errormap.c, src/libltfs/ltfs_error.h, src/libltfs/xml.h, src/libltfs/xml_writer.c, src/libltfs/xml_writer_libltfs.c
Refactor index write functions to report correct error code
Refactor index write functions to report correct error code
=> Refactor index write functions

src/tape_drivers/generic/file/filedebug_tc.c
Return correct value to tape_get_pews() in the filebackend. Actually correct PEW value is set against modeselect page=10.01.
Currently, a meda-data only writable tape created by the filebackend go back to return to writabel tape at the next mount. This fix make the filebackend to return PEW value correctly. That is used by libltfs mount sequence.
=> Fix PEW handling in the filebackend

messages/internal_error/root.txt, messages/libltfs/root.txt, messages/tape_linux_sg_ibmtape/root.txt
Correct wording of messages
- Corrections of messages
=> Correct wording of messages

messages/internal_error/root.txt, messages/libltfs/root.txt, messages/tape_linux_sg_ibmtape/root.txt
Tiny message correction
- Message correction
=> Tiny message correction

.travis.yml
This pull request includes auto build configuration by Travis CI kicked when
1. Push a change into the repository
2. Create a pull request
Currently the target is Ubuntu Xenial.
=> Support autobuild by Travis CI

src/libltfs/ltfs.h
Tiny correction of version string for OSX (make file build)
=> Update version number in ltfs.h

.travis.yml
=> Support CI build check on mac

.travis.yml
Check the PR or (code change) affected to the LTFS 3rd party backend project or not
Build the LTFS 3rd party backend project by Travis CI. The build will fail when the commit (or the PR) includes some changes to the backend I/F.
A committer must ask the contributor to change the code in the LTFS 3rd party backend project also.
=> Check backend I/F is suitable with the LTFS 3rd party backend project

src/libltfs/ltfs.h
Same as PR #120, but merged to master
=> Remove PACKAGE_XXX from ltfs.h

src/tape_drivers/generic/file/filedebug_tc.c
- Support IBM's TS1160 emulation in the file backend
- Improve IBM's TS11X0 emulation in the file backend
Previously, TS1160 is not supported in the file backend.
=> Improve the TS1160 handling in the file backend

src/libltfs/tape.c
Correct a code that creates a waning message
=> Correct a code to create a waning message

src/tape_drivers/ibm_tape.h
1. Ignore error when error table is not initialised
2. Remove a file accidentally commit in #156
=> Make a tiny fixes

messages/internal_error/root.txt, src/libltfs/arch/errormap.c, src/libltfs/ltfs_error.h
Add an error code for handling retry on ABORT errors.
=> Add an error code for retry

src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
Clear device name when path lost happens
Clear device name when path lost happens
=> Clear device name when path lost happens

.travis.yml, README.md
This pull request includes following changes. 
- Added build on Ubuntu Bionic
- Added build on ppc64le on Ubuntu builds
- Changed macOS image to xcode11.3
Build check refresh to follow tth new features of TravisCI.
=> Improve build cheker on TravisCI

.github/workflows/build-centos.yml, .github/workflows/build-centos7.yml, README.md
Introduce build cheker on CentOS7
=> Introduce build cheker on CentOS7

.github/workflows/build-debian9.yml, .github/workflows/build-fedora28.yml, README.md
Introduce Fedora28/Debian9 build checker
=> Introduce Fedora28/Debian9 build checker

.github/workflows/build-centos7.yml, .github/workflows/build-ubuntu-bionic.yml, .github/workflows/build-ubuntu-xeneal.yml, .travis.yml, README.md
Add several envronments to check build. 
=> Add several envronments to check build

.github/workflows/build-debian10.yml, .github/workflows/build-ubuntu-eoan.yml
Add Ubuntu19.10 and Debian10 build checker
=> Add Ubuntu19.10 and Debian10 build checker

.travis.yml
Re-enable ppc64le build checking.  This change also correct build break in macOS build on TravisCI.
=> Re-enable ppc64le build checking

src/tape_drivers/ibm_tape.c
There are multiple Product IDs for IBM enterprise tape.
=> Add 2 more entries for IBM enterprise tape

src/tape_drivers/ibm_tape.c, src/tape_drivers/linux/sg-ibmtape/.gitignore, src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c, src/tape_drivers/netbsd/scsipi-ibmtape/scsipi_ibmtape.c, src/tape_drivers/osx/iokit-ibmtape/iokit_ibmtape.c
Fix multiple memory leak on the tape drivers
=> Fix memory leak on the tape drivers

src/tape_drivers/ibm_tape.c
Added one more entry for TS1160
=> Added one more entry for TS1160

src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
Fix a segfault when sepcified device is invalid in the sg backend.
=> Fix segfault on the sg backend

src/libltfs/tape_ops.h, src/tape_drivers/generic/file/filedebug_tc.c, src/tape_drivers/ibm_tape.c, src/tape_drivers/ibm_tape.h, src/tape_drivers/tape_drivers.h
Experimental support of LTO9. 
Actually the drive is not available yet. But prepare the code with assumed definitions. That might be changed later.
=> Experimental support of LTO9

src/utils/ltfs_ordered_copy
Introduce the verbose mode into `ltfs_ordered_copy`
This PR implements following features.
* Introduce verbose mode
* Enhance progress indicator
Fixes #200
=> Introduce the verbose mode into `ltfs_ordered_copy`

.github/workflows/build-centos8.yml, .github/workflows/build-fedora28.yml, README.md
=> Add CentOS 8 to build checker

messages/tape_linux_sg/root.txt, src/tape_drivers/linux/sg/sg_tape.c
Tiny correction related into message.
=> Tiny correction

README.md
- Add docs for modprobe.d settings reboot requirement
Fixes #249
=> Document modprobe.d settings reboot requirement. Fixes #249

messages/internal_error/root.txt, src/libltfs/arch/errormap.c, src/libltfs/ltfs_error.h, src/tape_drivers/linux/lin_tape/lin_tape_ibmtape.c
Fix the build break of the lin_tape backend
=> Fix the build break of the lin_tape backend

README.md
- Fix of issue #270
I updated the description of README.md. Some descriptions are moved to the Wiki.
Fixes #270
- Refactoring
=> Update the README on master

src/tape_drivers/freebsd/cam/cam_cmn.h, src/tape_drivers/freebsd/cam/cam_tc.c
- Fix of issue #282 
Fixes #282
=> Fix a build break on FreeBSD

messages/libltfs/root.txt, src/libltfs/ltfs.c, src/libltfs/ltfs.h, src/libltfs/tape.c, src/libltfs/tape.h, src/libltfs/tape_ops.h, src/libltfs/xml_reader_libltfs.c, src/tape_drivers/freebsd/cam/cam_tc.c, src/tape_drivers/generic/file/filedebug_tc.c, src/tape_drivers/generic/itdtimg/itdtimg_tc.c, src/tape_drivers/linux/lin_tape/lin_tape_ibmtape.c, src/tape_drivers/linux/sg/sg_tape.c, src/tape_drivers/netbsd/scsipi-ibmtape/scsipi_ibmtape.c, src/tape_drivers/osx/iokit/iokit_tape.c
Refactor the functions for the RAO feature.
- Fix of issue #292 and #289.
- Simplify the logic of GRAO/RRAO in the sg backend
- Refactor arguments of the functions
- Refactor the members of `struct rao_mod`
- Flush the result file before making response
Fixes #292
Fixes #289
- Refactoring
=> Refactor RAO functions

src/tape_drivers/freebsd/cam/cam_tc.c, src/tape_drivers/linux/sg/sg_tape.c, src/tape_drivers/osx/iokit/iokit_tape.c, src/tape_drivers/vendor_compat.c, src/tape_drivers/vendor_compat.h
Fix bugs introduced into #296  
I should change one more place to support  Quantum type-B drive.
=> Fix bugs to fetch supported drive list

src/tape_drivers/hp_tape.c, src/tape_drivers/hp_tape.h, src/tape_drivers/vendor_compat.c
- Fix of issue #271 
Merge the patch reported in #271
Fixes #271
=> Experimental support of Tandberg drives

messages/libltfs/root.txt, src/libltfs/ltfs.c
Log more information about the index at writing index and mounting a tape
- Improvements
=> Log the generation of index at mount/unmount

configure.ac, src/libltfs/pathname.c
Modify build configuration
- Check ICU version and use unorm2 function automatically
- Make new lock architecture as default in all platforms
=> Modify build configuration

messages/libltfs/root.txt, messages/tape_linux_lin_tape/root.txt, src/kmi/flatfile.c, src/libltfs/arch/time_internal.h, src/libltfs/index_criteria.c, src/libltfs/ltfstrace.c, src/libltfs/ltfstrace.h, src/tape_drivers/linux/lin_tape/lin_tape_ibmtape.c
Fix a few vulnerabilities found by a scan tool.
=> Fix a few vulnerabilities

src/libltfs/index_criteria.c
Fix a potential buffer overflow
=> Fix a potential buffer overflow

src/tape_drivers/freebsd/cam/cam_tc.c
- Fix of issue #322
Fix build break in the cam backend.
Fixes #322
=> Fix build break in FreeBSD

README.md
Fix link breakage in README
- Fix of issue #339
Fixes #339
=> Fix link breakages in README

src/libltfs/xml_reader_libltfs.c
Fix a segmentation fault at parsing an extended attribute.
There are a few points to generate a crash when a parsing error on the `key` of an extended attribute.
Actually the code might touch to `xattr->key_name` after a parsing error happens at the `key` of an extended attribute.
In the fix, set `xattr` NULL and check it is not NULL when the code touch it.
=> Fix a crash at parsing an extended attribute

README.md
Fix typos in readme
Fix long-standing typos of homebrew in readme. 
readme file only
=> Fix typos of homebrew in readme

autogen.sh
From NeBSD's pkgsrc http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/filesystems/ltfs/patches/patch-autogen.sh?rev=1.1
=> Silence warnings from autoconf 2.70 and higher 

.github/workflows/codeql-analysis.yml, src/Makefile.am
Add `config_file.h` into installed headers.
I realized `config_file.h` is required for include `ltfs.h`
=> Install config_file.h as a header

src/tape_drivers/freebsd/cam/cam_tc.c
- Fix of issue #390 
there was error on line number 1247 about missing semicolon
Fixes #390 
=> Fix the build break on FreeBSD 12

LICENSE, messages/README
This pull request includes the following change:
- Update Copyright year in LICENSE and README
=> Update Copyright 2024

LICENSE, messages/README, src/libltfs/ltfs.c
=> Updating copyright for 2025
